// App context
export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const UPDATE_FILTER_SET = "UPDATE_FILTER_SET";
export const SET_INITIAL_FILTER_STATE = "SET_INITIAL_FILTER_STATE";
export const SET_INITIAL_ADD_JOB = "SET_INITIAL_ADD_JOB";
export const UPDATE_ADD_JOB = "UPDATE_ADD_JOB";
export const UPDATE_IS_LOGIN = "UPDATE_IS_LOGIN";
