// App context
export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const UPDATE_FILTER_SET = "UPDATE_FILTER_SET";
export const SET_INITIAL_FILTER_STATE = "SET_INITIAL_FILTER_STATE";
export const SET_INITIAL_ADD_JOB = "SET_INITIAL_ADD_JOB";
export const UPDATE_ADD_JOB = "UPDATE_ADD_JOB";
export const UPDATE_IS_LOGIN = "UPDATE_IS_LOGIN";
export const ADD_NEW_JOB = "ADD_NEW_JOB";
export const SET_ALL_JOBS = "SET_ALL_JOBS";
export const DELETE_JOB_ITEM = "DELETE_JOB_ITEM";
export const UPDATE_STATE = "UPDATE_STATE";
export const RESET_ADD_JOB = "RESET_ADD_JOB";
